const $=id=>document.getElementById(id),form=$('form');
const LF={mm:1,in:25.4},SF={MPa:1,ksi:6.894757293168},FF={N:1,kN:1000,lbf:4.4482216152605},TF={Nm:1,lbfft:1.3558179483314};
const fmt=(v,d=2)=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const force=n=>{const u=$('forceUnit').value;return`${fmt(n/FF[u])} ${u}`};const torque=nm=>$('torqueUnit').value==='lbfft'?`${fmt(nm/TF.lbfft)} lbf·ft`:`${fmt(nm)} N·m`;
let oldLength='mm',oldStrength='MPa';
function raw(){const ls=LF[$('lengthUnit').value],ss=SF[$('strengthUnit').value];return{diameterMm:Number($('diameter').value)*ls,pitchMm:Number($('pitch').value)*ls,stressAreaMm2:$('stressArea').value,proofStrengthMPa:Number($('proofStrength').value)*ss,preloadRatioPercent:$('preloadRatio').value,nutFactor:$('nutFactor').value,boltCount:$('boltCount').value,appliedTorque:$('appliedTorque').value,torqueUnit:$('torqueUnit').value}}
function syncArea(){if($('areaMode').value==='auto'){const x=raw();$('stressArea').value=Number(approximateStressArea(x.diameterMm,x.pitchMm).toFixed(4));$('stressArea').readOnly=true}else $('stressArea').readOnly=false}
function showErrors(e){const m={diameter:'diameter',pitch:'pitch',stressArea:'stressArea',proofStrength:'proofStrength',preloadRatio:'preloadRatio',nutFactor:'nutFactor',boltCount:'boltCount',appliedTorque:'appliedTorque'};Object.entries(m).forEach(([k,id])=>{$(id+'Error').textContent=e[k]||'';$(id).classList.toggle('invalid',!!e[k])});$('formError').hidden=!Object.keys(e).length;$('formError').textContent=Object.keys(e).length?'İşaretli alanları düzeltin.':''}
function render(){syncArea();const c=validateBolt(raw());showErrors(c.errors);if(!c.valid){['targetPreload','requiredTorque','proofLoad','totalClamp','targetStress','proofUtilization','usedArea','torqueRange'].forEach(id=>$(id).textContent='—');$('appliedPanel').hidden=true;return}const r=calculateBolt(raw());$('targetPreload').textContent=force(r.targetPreloadN);$('requiredTorque').textContent=torque(r.requiredTorqueNm);$('proofLoad').textContent=force(r.proofLoadN);$('totalClamp').textContent=force(r.totalClampN);$('targetStress').textContent=`${fmt(r.targetStressMPa)} MPa`;$('proofUtilization').textContent=`%${fmt(r.proofUtilizationPercent)}`;$('usedArea').textContent=`${fmt(r.stressAreaMm2)} mm²`;$('torqueRange').textContent=`${torque(r.torqueLowNm)} – ${torque(r.torqueHighNm)}`;$('appliedPanel').hidden=!r.applied;if(r.applied){$('estimatedPreload').textContent=force(r.applied.estimatedPreloadN);$('estimatedUtilization').textContent=`%${fmt(r.applied.proofUtilizationPercent)}`;$('preloadDifference').textContent=`${r.applied.differenceN>=0?'+':''}${force(r.applied.differenceN)}`}$('status').textContent=`K = ${$('nutFactor').value} varsayımıyla hesaplandı · motor v${BOLT_ENGINE_VERSION}`;$('calculatedAt').textContent=new Date().toLocaleString('tr-TR');window.currentBolt=r}
['diameter','pitch','stressArea','proofStrength','preloadRatio','nutFactor','boltCount','appliedTorque','torqueUnit','forceUnit'].forEach(id=>$(id).addEventListener('input',render));
$('areaMode').addEventListener('change',render);
$('lengthUnit').addEventListener('change',()=>{const n=$('lengthUnit').value,f=LF[oldLength]/LF[n];$('diameter').value=Number((Number($('diameter').value)*f).toPrecision(10));$('pitch').value=Number((Number($('pitch').value)*f).toPrecision(10));$('pitchUnit').textContent=n;oldLength=n;render()});
$('strengthUnit').addEventListener('change',()=>{const n=$('strengthUnit').value;$('proofStrength').value=Number((Number($('proofStrength').value)*SF[oldStrength]/SF[n]).toPrecision(10));oldStrength=n;render()});
$('reset').addEventListener('click',()=>{Object.entries({diameter:12,pitch:1.75,stressArea:84.27,proofStrength:600,preloadRatio:75,nutFactor:.2,boltCount:1,appliedTorque:'',lengthUnit:'mm',strengthUnit:'MPa',areaMode:'manual',torqueUnit:'Nm',forceUnit:'kN'}).forEach(([k,v])=>$(k).value=v);oldLength='mm';oldStrength='MPa';$('pitchUnit').textContent='mm';render()});
$('csv').addEventListener('click',()=>{if(!window.currentBolt)return;const r=window.currentBolt,x=raw(),rows=[['Alan','Değer','Birim'],['Proje',$('project').value,''],['Hesap no',$('calculationNo').value,''],['Hazırlayan',$('preparedBy').value,''],['Nominal çap',x.diameterMm,'mm'],['Diş adımı',x.pitchMm,'mm'],['Çekme alanı',x.stressAreaMm2,'mm²'],['Kanıt dayanımı',x.proofStrengthMPa,'MPa'],['Ön yük oranı',x.preloadRatioPercent,'%'],['Tork katsayısı',x.nutFactor,''],['Hedef ön yük',r.targetPreloadN,'N'],['Gerekli tork',r.requiredTorqueNm,'N·m']];const csv='\uFEFF'+rows.map(a=>a.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='civata-on-yuk.csv';a.click();URL.revokeObjectURL(a.href)});
$('print').addEventListener('click',()=>window.print());form.addEventListener('submit',e=>e.preventDefault());render();
